Avoid compiler casting warnings by using the correct type
sudo-project/sudo pull request #265
Opened 2023-05-18 18:52 UTC by AtariDreams

This saves casting and compile warnings related to casts.

2023-06-21 19:42 UTC, millert commented
Are you using gcc's -Wconversion or something similar to find these?  Some of the changes are OK but others would break the plugin or library ABI which is not OK.  Also, some of the non-trivial changes introduce bugs.

2023-06-26 16:44 UTC, AtariDreams commented
@millert Fixed!

2023-06-26 22:51 UTC, millert requested changes

2023-06-26 22:51 UTC, millert commented on lib/util/strtoid.c
> +	if (ret == (id_t)-1 || !valid_separator(p, ep, sep)) {
This needs to stay.  On some systems id_t is a signed 64-bit integer so both -1 and UINT_MAX are possible.

2023-06-26 22:51 UTC, millert commented on plugins/sudoers/getdate.c
> -  int days = (
This change needs to be made to getdate.y as well.

2023-06-27 02:23 UTC, AtariDreams commented on lib/util/explicit_bzero.c
> +	*s++ = 0;
char casted to unsigned char

2023-06-27 02:28 UTC, AtariDreams commented
@millert Done!

2023-06-27 16:15 UTC, millert requested changes
Just two minor issues.

2023-06-27 16:15 UTC, millert commented on lib/eventlog/eventlog.c
> -    argv[i] = NULL;
The manual NULL termination of the array is still needed here.

2023-06-27 16:15 UTC, millert commented on src/limits.c
> +    free(info[--nstored]);
Please indent the free() call here.

2023-06-28 20:36 UTC, AtariDreams commented
@millert Done!

2023-06-29 16:06 UTC, merged