Regenerate toke using updated flex
sudo-project/sudo pull request #279
Opened 2023-06-29 18:39 UTC by AtariDreams

Use the current version of flex to generate toke.c

2023-06-30 19:25 UTC, millert requested changes

2023-06-30 19:25 UTC, millert commented on plugins/sudoers/toke.l
> +    if (count <= 0) {
Now that it is size_t, count cannot be < 0 do this change should be dropped.

2023-06-30 19:25 UTC, millert commented on plugins/sudoers/toke.l
> +    if (count) {
Another case where count cannot be < 0 so the original code is correct.

2023-06-30 19:25 UTC, millert commented on plugins/sudoers/toke.l
> -	    size -= n;
There is no need to change the order here.  I prefer it the way it currently is.

2023-06-30 19:25 UTC, millert commented on plugins/sudoers/toke.l
> -	    size--;
There is no need to change the order here.  I prefer it the way it currently is.

2023-07-01 15:47 UTC, AtariDreams commented
@millert Done!

2023-07-01 16:23 UTC, millert approved these changes
Looks good to me

2023-07-01 16:23 UTC, merged