Fixed even more signedness and conversion issues
sudo-project/sudo pull request #283
Opened 2023-07-03 18:37 UTC by AtariDreams

This should be the last of them.

2023-07-03 21:28 UTC, millert requested changes

2023-07-03 21:28 UTC, millert commented on lib/util/sudo_debug.c
> +	"<- %s @ %s:%d := %ld", func, file, line, (long)ret);
I don't see a need for this change.  If `id_t` is 32-bits, printing it as an int should be fine.

2023-07-03 21:28 UTC, millert commented on lib/util/sudo_debug.c
> +	"<- %s @ %s:%d := %ld", func, file, line, (long)ret);
Same here, a 32-bit time_t will fit into an int, there is no need to use a long.

2023-07-03 21:28 UTC, millert commented on plugins/sudoers/toke.c
> -#line 3 "toke.c"
Please drop changes to this file, your version of flex and mine appear to disagree on line numbers.

2023-07-04 01:37 UTC, AtariDreams commented
@millert Done!

2023-07-04 01:54 UTC, millert requested changes

2023-07-04 01:54 UTC, millert commented on lib/iolog/iolog_mkdirs.c
> +		if (uid_changed) {
The changes to this file should be dropped, the code is correct as-is.  We want to display a warning when the initial mkdirat() fails if we don't retry after swapping ids.

2023-07-04 02:07 UTC, AtariDreams commented
@millert Done!

2023-07-04 02:09 UTC, millert approved these changes

2023-07-04 02:09 UTC, merged