Give every printf like function __restrict for the format value
sudo-project/sudo pull request #287
Opened 2023-07-07 20:10 UTC by AtariDreams

The format value has to be a string literal, every time.

Otherwise, you are not using these functions correctly. To reinforce this fact, I putrestrict over every non-contrib example of this I could find.

2023-07-07 21:06 UTC, millert requested changes
Please try to keep unrelated changes separate.

2023-07-07 21:06 UTC, millert commented on lib/eventlog/logwrap.c
> -	    debug_return_ssize_t(-1);
These return type changes are unrelated and should not be part of this PR.

2023-07-07 21:06 UTC, millert commented on plugins/sudoers/ldap_util.c
> -			bool converted = sudoers_defaults_to_tags(var, val, op,
This hunk is unrelated and should not be part of this PR

2023-07-07 21:06 UTC, millert commented on plugins/sudoers/ldap_util.c
> -    *dst = '\0';
This hunk is unrelated and should not be part of this PR.

2023-07-07 23:21 UTC, AtariDreams commented
Please hold on as there are formatting changes I need to undo.

2023-07-08 01:47 UTC, millert approved these changes

2023-07-08 01:48 UTC, merged